name: CI-CD to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: devopsacrlab001
  IMAGE_NAME: sampleapp
  RESOURCE_GROUP: rg-devops-lab
  CLUSTER_NAME: DevopsAKSCluster

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name $ACR_NAME

    - name: Build and Push Docker Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} ./sampleapp
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/myisoapp myisoapp=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
